#!/bin/bash

cat /etc/hosts.base <(join -t$'\t' -12 -21 <(sort /var/bocker/ps_*/var/tmp/instance-tag) <(sort env-mapping) | join -t$'\t' -13 -21 - <(sort service-mapping) | sort -k3,3 -n | awk '{def[$1,$2]=sprintf("%s\t%s%s", $4, $5 ? $5"-" : "", $6);} END {for(k in def){print def[k];}}')
