#!/bin/bash

# gather instance tags from containers running on the current machine
# expects tags to exist in '/var/tmp/instance-tag' on containers.
#
# instance tag files have the format of:
#   <timestamp> <environment> <service-name> <ip>
#
# example:
#   1447913712.994965273 UAT-Murray api-service-application 11.0.0.251

fn_fmt () {
  awk '{
    def[$1,$2]=sprintf("%s\t%s%s", $4, $5 ? $5"-" : "", $6);
  } END {
    for(k in def){
      print def[k];
    }
  }'
}

fn_dedupe () {
  join -t$'\t' -12 -21 \
    <(sort /var/bocker/ps_*/var/tmp/instance-tag) \
    <(sort env-mapping) \
    | join -t$'\t' -13 -21 - <(sort service-mapping) \
    | sort -k3,3 -n \
    | fn_fmt
}

cat /etc/hosts.base "$(fn_dedupe)"
