#!/bin/sh

/bin/rm -f /dev/null /dev/zero /dev/random /dev/urandom /dev/stdin /dev/stdout /dev/stderr
/bin/mount -t proc proc /proc
/bin/mknod -m 666 /dev/null c 1 3
/bin/mknod -m 666 /dev/zero c 1 5
/bin/mknod -m 666 /dev/random c 1 8
/bin/mknod -m 666 /dev/urandom c 1 9
/bin/ln -s /proc/self/fd/0 /dev/stdin
/bin/ln -s /proc/self/fd/1 /dev/stdout
/bin/ln -s /proc/self/fd/2 /dev/stderr
