#!/bin/sh

# display a help message
cat << USAGE
  Usage: shocker [options] <command>

  commit, cleanup, exec, export, images,
  init, kill, logs, name, ps, pull, rm,
  route, run, spawn, stop

  Options:
    -h, --help     output usage information
    -v, --version  output version information

  Examples:
    shocker pull alpine latest   # fetch the latest alpine linux image
    shocker init                 # create a new container
    shocker exec                 # run a command in shocker
USAGE
