#!/bin/sh
dirname=$(dirname "$(readlink -f "$0")")

#shellcheck disable=SC1090
. "$dirname"/utils.sh

usage () {
cat << USAGE
  shocker-image-create - create an image

  Usage: shocker image create <dir|image|container> [tar-archive [...]]

  Options:
   -h, --help output usage information

  Examples:
   $ shocker image create .             # create a new image from current dir
   $ shocker image create . archive.tgz # create a new image from current dir
                                        # with archive.tgz layed over it
USAGE
}

[ "$#" -eq 0 ] && { usage; exit 1; }
case "$1" in
  -h|--help ) usage && exit 1 ;;
esac

# generate image id
while true; do
    uuid="$(mktemp -u img_XXXXX)"
    [ ! -e "${image_path}/${uuid}" ] && break
done

# create new empty subvolume
btrfs subvolume create "${image_path}/${uuid}" > /dev/null

# copy (using reflink) all files in source dir to image dir
find "$1" -mindepth 1 -maxdepth 1 -print0 | xargs -0 cp -prf --reflink=auto -t "${image_path}/${uuid}" >/dev/null

# save image meta data
readlink -f "$1" > "${image_path}/${uuid}/img.source"

# extract all tarballs over image directory
shift
for tarball in "$@"; do
    [ -r "$tarball" ] || break;
    tar xaf "$tarball" -C "${image_path}/${uuid}"
done

printf "Created: %s\n" "$uuid"
