#!/bin/sh
btrfs_path='/var/shocker'
dirname=$(dirname "$(readlink -f "$0")")

# source helper utils
. "$dirname"/utils.sh

usage () {
cat << USAGE
  shocker-exec - execute a command in a running container

  Usage: shocker exec <container_id> <command>

  Options:
   -h, --help   output usage information

  Examples:
   $ shocker exec ps_1234 'ls ~/'
USAGE
}

case "$1" in
  -h|--help ) usage && exit 0;;
esac

[ "$#" -eq 2 ] || { usage; exit 1; }

shocker_exists "$1"
if [ "$?" -ne 0 ]; then
  printf "No container named '%s' exists\n" "$1" >&2
  exit 1
fi

fn_mine () {
  ppid="$(pgrep -f "unshare.*$1")"
  ps ao ppid,pid \
    | awk -v ppid="$ppid" '$1 == ppid {print $2}'
}

cid="$(fn_mine "$1")"
shocker_running "$1"
if [ "$?" -ne 0 ]; then
  printf "Container '%s' exists but is not running\n" "$1" >&2
  exit 1
fi

nsenter -t "$cid" -m -u -i -n -p chroot "$btrfs_path/$1" "${@:2}"
