#!/bin/bash
dirname=$(dirname "$(readlink -f "$0")")

# source helper utils
. "$dirname"/utils.sh

usage () {
cat << USAGE
  shocker-route - ensure outgoing route exists for containers

  Usage: shocker route <network-device>

  Options:
   -h, --help output usage information

  Examples:
    $ shocker route eth0   # expose the eth0 device
USAGE
}

[ "$#" -eq 1 ] || { usage; exit 1; }
case "$1" in
  -h|--help ) usage && exit 1 ;;
esac

GATEWAY="$(get_gateway)"
NETWORK="$(get_network)"
BRIDGE_DEV="$(get_bridge_dev)"
MASK="$(get_mask)"

ip link add "$BRIDGE_DEV" type bridge || true
ip addr add "$(int_to_ip "$GATEWAY")/$MASK" dev "$BRIDGE_DEV"
ip link set "$BRIDGE_DEV" up

iptables \
  -t nat \
  -A POSTROUTING \
  -s "$(int_to_ip "$NETWORK")/$MASK" \
  -o "$1" \
  -j MASQUERADE
