#!/bin/sh
readonly btrfs_path='/var/shocker'
readonly dirname=$(dirname "$(readlink -f "$0")")

#shellcheck disable=SC1090
. "$dirname"/utils.sh

usage () {
cat << USAGE
  shocker-commit - commit a container to an image

  Usage: shocker commit <container_id> <image_id>

  Options:
   -h, --help output usage information

  Examples:
   $ shocker commit 1235 6787  # commit a container to an image
USAGE
}

[ "$#" -eq 1 ] || { usage; exit 1; }
case "$1" in
  -h|--help ) usage && exit 1 ;;
esac

shocker_exists "$1"
if [ "$?" -ne 0 ]; then
  printf "No container named '%s' exists\n" "$1" >&2
  exit 1
fi

shocker_exists "$2"
if [ "$?" -ne 0 ]; then
  printf "No image named '%s' exists\n" "$2" >&2
  exit 1
fi

readonly p1="$btrfs_path/$1"
readonly p2="$btrfs_path/$2"
shocker_rm "$2" && btrfs subvolume snapshot "$p1" "$p2" > /dev/null
echo "Created: $2"
