#!/bin/sh
btrfs_path='/var/shocker'
cgroups='cpu,cpuacct,memory'
dirname=$(dirname "$(readlink -f "$0")")

# source helper utils
#shellcheck disable=SC1090
. "$dirname"/utils.sh

usage () {
cat << USAGE
  shocker-remove - remove container
  Usage: shocker remove <container-id>

  Options:
    -h, --help output usage information

  Examples:
    $ shocker remove ps_1234  # delete 'ps_1234'
USAGE
}

[ "$#" -eq 1 ] || { usage; exit 1; }
case "$1" in
  -h|--help ) usage && exit 1 ;;
esac

shocker_exists "$1"
if [ "$?" -ne 0 ]; then
  printf "No container named '%s' exists\n" "$1" >&2
  exit 1
fi

ctype=$(get_type "$1")
if [ "$ctype" != "container" ]; then
    printf "'%s' is not a container\n" "$1" >&2
    exit 1
fi

btrfs subvolume delete "$btrfs_path"/"$1" > /dev/null
cgdelete -g "$cgroups":/"$1" > /dev/null 2>&1
