#!/bin/sh
btrfs_path='/var/shocker'
cgroups='cpu,cpuacct,memory'

. ./utils.sh

usage () {
cat << USAGE
  shocker-rm - remove stored images or containers
  Usage: shocker rm <image-id>|<container-id>

  Options:
    -h, --help output usage information

  Examples:
    $ shocker rm img_1234  # delete 'img_1234'
USAGE
}

[ "$#" -eq 1 ] || { usage; exit 1; }
case "$1" in
  -h|--help ) usage && exit 1 ;;
esac

shocker_check "$1" > /dev/null
if [ "$?" -ne 0 ]; then
  printf "No container named '%s' exists\n" "$1"
  exit 1
fi

btrfs subvolume delete "$btrfs_path"/"$1" > /dev/null
cgdelete -g "$cgroups":/"$1" > /dev/null 2>&1 || true
printf "Removed: %s\n" "$1"
