#!/bin/sh
btrfs_path='/var/shocker'
cgroups='cpu,cpuacct,memory'

. ./utils.sh

usage () {
cat << USAGE
  shocker-cleanup - cleanup unused cgroups, namespaces and veth devices

  Usage: shocker cleanup

  Options:
   -h, --help output usage information

  Examples:
   $ shocker cleanup
USAGE
}

case "$1" in
  -h|--help ) usage && exit 1 ;;
esac
[ "$#" -eq 0 ] || { usage; exit 1; }

#shellcheck disable=SC2012
ls -rtd "$btrfs_path"/ps_* | while read -r ps; do
  ps=$(basename "$ps")
  if [ "$(get_state "$ps")" = "crashed" ]; then
    findmnt -r | grep "^$ps/" | cut -f1 -d' ' | xargs umount || true
    ip link del "veth0_$ps" >/dev/null 2>&1 || true
    ip netns del "netns_$ps" >/dev/null 2>&1 || true
    cgdelete -g "$cgroups:/$ps" >/dev/null 2>&1 || true
    echo "Cleaned '$ps'"
  fi
done
