#!/bin/sh
btrfs_path='/var/shocker'
dirname=$(dirname "$(readlink -f "$0")")

# source helper utils
. "$dirname"/utils.sh

usage () {
cat << USAGE
  shocker-logs - view logs from a container

  Usage: shocker logs <container_id>

  Options:
   -h, --help output usage information

  Examples:
USAGE
}

[ "$#" -eq 1 ] || { usage; exit 1; }
case "$1" in
  -h|--help ) usage && exit 1 ;;
esac

shocker_exists "$1"
if [ "$?" -ne 0 ]; then
  printf "No container named '%s' exists\n" "$1" >&2
  exit 1
fi

cat "$btrfs_path/$1/$1.log"
