#!/bin/sh
dirname=$(dirname "$(readlink -f "$0")")

#shellcheck disable=SC1090
. "$dirname"/utils.sh

usage () {
cat << USAGE
  shocker-commit - commit a container to an image

  Usage: shocker commit <container_id> <image_id>

  Options:
   -h, --help output usage information

  Examples:
   $ shocker commit 1235 6787  # commit a container to an image
USAGE
}

[ "$#" -eq 2 ] || { usage; exit 1; }
case "$1" in
  -h|--help ) usage && exit 1 ;;
esac

shocker_container_exists "$1"
if [ "$?" -ne 0 ]; then
  printf "No container named '%s' exists\n" "$1" >&2
  exit 1
fi

shocker_image_exists "$2"
if [ "$?" -ne 0 ]; then
  printf "No image named '%s' exists\n" "$2" >&2
  exit 1
fi

container="${container_path}/$1"
image="${image_path}/$2"
"${dirname}/shocker-image-remove" "$2" && btrfs subvolume snapshot "$container" "$image" > /dev/null
echo "Created: $2"
