#!/bin/sh

# display a help message
cat << USAGE
  Usage: shocker [options] <command>

  commit, cleanup, exec, export, images,
  init, kill, limit, logs, name, ps,
  pull, rm, route, run, spawn, stop

  Options:
    -h, --help     output usage information
    -v, --version  output version information

  Examples:
    $ shocker pull -h              # output usage for the pull command
    $ shocker pull alpine latest   # fetch the latest alpine linux image
    $ shocker images               # list local images
    $ shocker run img_1235 ash     # start an ash shell from an image
USAGE
