#!/bin/sh
btrfs_path='/var/shocker'
cgroups='cpu,cpuacct,memory'
dirname=$(dirname "$(readlink -f "$0")")

# source helper utils
#shellcheck disable=SC1090
. "$dirname"/utils.sh

usage () {
cat << USAGE
  shocker-image-rm - remove stored images
  Usage: shocker image remove <image-id>

  Options:
    -h, --help output usage information

  Examples:
    $ shocker image remove img_1234  # delete 'img_1234'
USAGE
}

[ "$#" -eq 1 ] || { usage; exit 1; }
case "$1" in
  -h|--help ) usage && exit 1 ;;
esac

shocker_image_exists "$1"
if [ "$?" -ne 0 ]; then
  printf "No image named '%s' exists\n" "$1" >&2
  exit 1
fi

btrfs subvolume delete "${image_path}/$1" > /dev/null
cgdelete -g "$cgroups":/"$1" > /dev/null 2>&1
printf "Removed: %s\n" "$1"
