#!/bin/sh

# display a help message
cat << USAGE
  Usage: shocker [options] <command>

  Commands:
    commit, exec, help, image, init,
    kill, logs, ps, pull, rm, run,
    spawn

  Options:
    -h, --help     output usage information
    -v, --version  output version information

  Examples:
    shocker pull alpine latest   # fetch the latest alpine linux image
    shocker init                 # create a new container
    shocker exec                 # run a command in shocker
USAGE
