#!/bin/sh

. "$(dirname $(readlink -f "$0"))/utils.sh"

usage () {
cat << USAGE
  shocker-image-list - list images
  Usage: shocker image list

  Options:
   -h, --help output usage information

  Examples:
   $ shocker image list   # list images
USAGE
}

case "$1" in
  -h|--help ) usage && exit 1 ;;
esac
[ "$#" -eq 0 ] || { usage; exit 1; }

# print list of available images
{ printf "IMAGE_ID\tSOURCE\n";
  for img in "${image_path}"/*; do
    if [ -e "$img" ] && [ -e "$img/img.source" ]; then
      img_id="$(basename "$img")"
      img_source="$(cat "/$img/img.source")"
      printf "%s\t%s\n" "$img_id" "$img_source"
    fi
  done; } | column -t
