#!/bin/sh
dirname=$(dirname "$(readlink -f "$0")")
. "$dirname"/utils.sh

usage () {
cat << USAGE
  shocker-kill - kill a running container

  Usage: shocker kill <container-id> [signal]

  Options:
   -h, --help output usage information

  Examples:
   $ shocker kill ps_1234 SIGKILL  # terminate container 'ps_1234'
USAGE
}

[ "$#" -eq 1 ] || { usage; exit 1; }
case "$1" in
  -h|--help ) usage && exit 1 ;;
esac

shocker_exists "$1"
if [ "$?" -ne 0 ]; then
  printf "No container named '%s' exists\n" "$1" >&2
  exit 1
fi

state=$(get_state "$1")
case $state in
  stopped) printf "Container '%s' is already stopped\n" "$1" ;;
  crashed) printf "Container '%s' has crashed, use 'shocker-cleanup\n'" "$1" ;;
  missing) printf "Container '%s' does not exist\n" "$1" ;;
esac

sort -nr "/sys/fs/cgroup/cpuacct/$1/tasks" | while read -r proc; do
  kill -SIGKILL -- "$proc" 2>/dev/null || true;
done
