#!/usr/bin/env sh
btrfs_path='/var/shocker'
dirname=$(dirname "$(readlink -f "$0")")

if [ "$(id -u)" -ne 0 ]; then
  printf "shocker(1) should be executed as sudo\n" >&2
  exit 1
fi

# check if btrfs is mounted and available
if [ ! -d "$btrfs_path" ]; then
  printf 'Error: %s does not exist\n' "$btrfs_path" >&2
  exit 1
fi
sudo btrfs filesystem show "$btrfs_path" > /dev/null
if [ "$?" -ne 0 ]; then
  printf 'Error: %s is not a btrfs filesystem\n' "$btrfs_path" >&2
  exit 1
fi

# source utility functions
#shellcheck disable=SC1090
. "$dirname"/utils.sh

usage () {
cat << USAGE
  Usage: shocker [options] <command>

  commit, cleanup, exec, export, images,
  init, kill, limit, logs, name, ps,
  pull, rm, route, run, spawn, stop

  Options:
    -h, --help     output usage information
    -v, --version  output version information

  Examples:
    $ shocker pull -h              # output usage for the pull command
    $ shocker pull alpine latest   # fetch the latest alpine linux image
    $ shocker images               # list local images
    $ shocker run img_1235 ash     # start an ash shell from an image
USAGE
}

shocker_image() {
    case "$1" in
      -h|--help ) usage && exit 0 ;;
      list|ls   ) shift && "$dirname/shocker-image-list" "$@" ;;
      pull      ) shift && "$dirname/shocker-image-pull" "$@" ;;
      create    ) shift && "$dirname/shocker-image-create" "$@" ;;
      change    ) shift && "$dirname/shocker-image-change" "$@" ;;
      remove|rm ) shift && "$dirname/shocker-image-remove" "$@" ;;
      *         ) usage && exit 1 ;;
    esac
}

[ "$#" -ne 0 ] || { usage; exit 1; }
case "$1" in
  -h|--help ) usage && exit 0 ;;
  image     ) shift && shocker_image "$@" ;;
  commit    ) shift && "$dirname/shocker-commit" "$@" ;;
  cleanup   ) shift && "$dirname/shocker-cleanup" "$@" ;;
  exec      ) shift && "$dirname/shocker-exec" "$@" ;;
  export    ) shift && "$dirname/shocker-export" "$@" ;;
  kill      ) shift && "$dirname/shocker-kill" "$@" ;;
  limit     ) shift && "$dirname/shocker-limit" "$@" ;;
  logs      ) shift && "$dirname/shocker-logs" "$@" ;;
  name      ) shift && "$dirname/shocker_name" "$@" ;;
  ps        ) shift && "$dirname/shocker-ps" "$@" ;;
  rm        ) shift && "$dirname/shocker-rm" "$@" ;;
  route     ) shift && "$dirname/shocker-route" "$@" ;;
  run       ) shift && shocker_run "$@" ;;
  spawn     ) shift && shocker_spawn "$@" ;;
  start     ) shift && "$dirname/shocker-start" "$@" ;;
  stop      ) shift && "$dirname/shocker-stop" "$@" ;;
  *         ) usage && exit 1 ;;
esac
