#!/bin/sh
readonly btrfs_path='/var/shocker'

usage () {
cat << USAGE
  shocker-images - list images
  Usage: shocker images

  Options:
   -h, --help output usage information

  Examples:
   $ shocker images   # list images
USAGE
}

case "$1" in
  -h|--help ) usage && exit 1 ;;
esac
[ "$#" -eq 0 ] || { usage; exit 1; }

# check if images exist
for img in "$btrfs_path"/img_*; do
  [ -e "$img/img.source" ] && break
  printf 'No images found in %s\n' "$btrfs_path" >&2
  exit 0
done

# print list of available images
printf "IMAGE_ID\t\tSOURCE\n"
for img in "$btrfs_path"/img_*; do
  if [ -e "$img" ]; then
    readonly img_id="$(basename "$img")"
    readonly img_source="$(cat "/$img/img.source")"
    printf "%s\t\t%s\n" "$img_id" "$img_source"
  fi
done
