#!/bin/bash
dirname=$(dirname "$(readlink -f "$0")")

#shellcheck disable=SC1090
. "$dirname"/utils.sh

shocker_init () {
  [ -d "$1" ] || { printf "No directory named '%s' exists\n" "$1" >&2; exit 1; }

  while true; do
    uuid="$(mktemp -u img_XXXXX)"
    [ ! -e "${image_path}/${uuid}" ] && break;
  done

  btrfs subvolume create "${image_path}/${uuid}" > /dev/null
  cp -rf --reflink=auto "$1"/* "${image_path}/${uuid}" > /dev/null
  [ -f "${image_path}/${uuid}"/img.source ] || {
    echo "$1" > "${image_path}/${uuid}"/img.source
  }

  echo "$(cat "${image_path}/${uuid}/img.source")" "$(date +%s)" "$RANDOM" \
    | md5sum | cut -f1 -d' ' > "${image_path}/${uuid}/.tree"

  printf "Created: %s\n" "$uuid"
}

#HELP Pull an image from Docker Hub:\nSHOCKER pull <name> <tag>
[ -d '/tmp' ] || { printf 'Error: /tmp does not exist\n' >&2; exit 1; }
[ "$#" -eq 2 ] || {
  printf 'Usage: shocker pull <image> <version>\n'
  exit 1
}

fn_get_registry () {
 curl -sL -o /dev/null -D- \
   -H 'X-Docker-Token: true' \
   "https://index.docker.io/v1/repositories/$1/images" \
   | tr -d '\r' \
   | awk -F ': *' '$1 == "X-Docker-Token" { print $2 }'
}

fn_get_id () {
 curl -sL -H "Authorization: Token $token" \
   "$registry/repositories/$1/tags/$2" \
   | sed 's/"//g'
}

fn_get_ancestry () {
 curl -sL \
  -H "Authorization: Token $token" \
  "$registry/images/$id/ancestry"
}

token="$(fn_get_registry "$1")"
registry='https://registry-1.docker.io/v1'
id="$(fn_get_id "$1" "$2")"
[ "${#id}" -ne 64 ] && echo "No image named '$1:$2' exists" >&2 && exit 1

ancestry="$(fn_get_ancestry)"
IFS=','
ancestry=(${ancestry//[\[\] \"]/})

IFS=' \n\t'
tmp_uuid="img_$RANDOM"
mkdir /tmp/"$tmp_uuid"
for id in "${ancestry[@]}"; do
  curl -#L -H "Authorization: Token $token" \
    "$registry/images/$id/layer" \
    -o /tmp/"$tmp_uuid"/layer.tar
  tar xf /tmp/"$tmp_uuid"/layer.tar -C /tmp/"$tmp_uuid"
  rm /tmp/"$tmp_uuid"/layer.tar
done

echo "$1:$2" > /tmp/"$tmp_uuid"/img.source
shocker_init /tmp/"$tmp_uuid"
rm -rf /tmp/"$tmp_uuid"
