#!/bin/bash
btrfs_path='/var/shocker'
dirname=$(dirname "$(readlink -f "$0")")

# source helper utils
. "$dirname"/utils.sh

usage () {
cat << USAGE
  shocker-ps - list containers
  Usage: shocker ps

  Examples:
   $ shocker ps   # list container
USAGE
}

[ "$#" -eq 0 ] || { usage; exit 1; }

file_count="$(find "$btrfs_path" -maxdepth 1 -type d -name 'ps_*' | wc -l)"
if [ "$file_count" -eq 0 ]; then
  printf "No running containers\n" >&2
  exit 0
fi

printf "%-12s    %8s    %-18s    %s\n" 'CONTAINER_ID' 'STATE' 'IP' 'COMMAND'

for ps in "$btrfs_path"/ps_*; do
  [ -e "$ps" ] || break

  ps=$(basename "$ps")
  state=$(get_state "$ps")
  ip=-

  case $state in
    running)
      ansi="1;32"
      ip=$(ip netns exec "netns_$ps" ip addr 2>/dev/null \
        | sed -n "s/.*inet \([^ ]\+\) .* veth1_$ps/\1/p" \
        | tr -d "\n")
      ;;
    crashed) ansi="1;31";;
    *      ) ansi="0";;
  esac

  cmd="$(cat "$btrfs_path/$ps/$ps.cmd")"
  printf "%-12s    \x1b[%sm%8s\x1b[0m    %-18s    %s\n" "$ps" "$ansi" "$state" "$ip" "$cmd"
done
