#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

for img in $(./shocker images | grep 'img' | awk '{print $1}'); do
	./shocker rm "$img"
done

for ps in $(./shocker ps | grep 'ps' | awk '{print $1}'); do
	./shocker rm "$ps"
done
