#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

img="$(./shocker init ~/base-image | awk '{print $2}')"
./shocker images | grep -qw "$img"
[[ "$?" == 0 ]]

# ▼ ▼ ▼ Race condition waiting to happen ▼ ▼ ▼
./shocker run "$img" "sleep 5 && ps aux" &
sleep 2
ps="$(./shocker ps | grep 'sleep 5' | awk '{print $1}')"
exec="$(./shocker exec "$ps" ps aux | wc -l)"
[[ "$exec" == "4" ]]
sleep 3
# ▲ ▲ ▲ Race condition waiting to happen ▲ ▲ ▲

./shocker run "$img" ps aux
ps="$(./shocker ps | grep 'ps aux' | awk '{print $1}')"
exec="$(./shocker exec "$ps" ps aux)" || true
[[ "$exec" == "Container '$ps' exists but is not running" ]]

exec="$(./shocker exec foo ps aux)" || true
[[ "$exec" == "No container named 'foo' exists" ]]
