#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

centos_img="$(./shocker pull centos 7 2> /dev/null | awk '{print $2}')"
./shocker run "$centos_img" cat /etc/redhat-release
ps="$(./shocker ps | grep 'cat /etc/redhat-release' | awk '{print $1}')"
logs="$(./shocker logs "$ps")"
./shocker rm "$ps"
[[ "$logs" == "CentOS Linux release 7"* ]]

ubuntu_img="$(./shocker pull ubuntu 14.04 2> /dev/null | awk '{print $2}')"
./shocker run "$ubuntu_img" tail -n1 /etc/lsb-release
ps="$(./shocker ps | grep 'tail -n1 /etc/lsb-release' | awk '{print $1}')"
logs="$(./shocker logs "$ps")"
./shocker rm "$ps"
[[ "$logs" == *"Ubuntu 14.04"* ]]
