#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

img="$(./shocker init ~/base-image | awk '{print $2}')"
cmd="echo $RANDOM"
./shocker run "$img" "$cmd"
ps="$(./shocker ps | grep "$cmd" | awk '{print $1}')"

[[ "$(./shocker images | grep -c "$img")" == 1 ]]
[[ "$(./shocker ps | grep -c "$cmd")" == 1 ]]

./shocker rm "$img"
./shocker rm "$ps"

[[ "$(./shocker images | grep -c "$img")" == 0 ]]
[[ "$(./shocker ps | grep -c "$cmd")" == 0 ]]
